### ISSUE TITLE
Move EIS work into its own project

### ISSUE THREAD

**Issue by wdenton** [guerrilla-archiving/eot-sprint-toolkit#13]
I suggest moving the EIS work out of here and putting it together with @sonalranjit's WARC-maker into a new project, where all the parts can be tweaked to fit together nicely.

**Comment by wdenton** [comment]
(I'm happy to get it it started if people agree, but I don't have write access.)

**Comment by titaniumbones** [comment]
Just gave you write access to both repos -- sorry, I haven't really figured out the permissions system here on these teams, will be a little slow optimizing.

and thanks!

**Comment by wdenton** [comment]
It's all moved here: https://github.com/guerrilla-archiving/epa-eis

You can delete the eis directory.

**Comment by titaniumbones** [comment]
done. thx @wdenton and others!
